### ISSUE TITLE
npm ERROR

### ISSUE THREAD

**Issue by kimsijin33** [brandiqa/sp-mall-park-wrld#1]
I'm gonna npm start but occured below error
How can I fix it?
please help me

Thank you

(xxx) root@xxxx:/home/anacoxxnda/sp-mall-park-wrld-master# npm start

> mallmap@1.0.0 start /home/anaconda/sp-mall-park-wrld-master
> parcel src/index.html

sh: 1: parcel: not found

npm ERR! Linux 5.4.0-65-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! mallmap@1.0.0 start: `parcel src/index.html`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the mallmap@1.0.0 start script 'parcel src/index.html'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mallmap package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     parcel src/index.html
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mallmap
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mallmap
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/anaconda/sp-mall-park-wrld-master/npm-debug.log

**Comment by brandiqa** [comment]
Follow the instructions I've written in README.md file. You haven't
installed Parcel
