### ISSUE TITLE
I'm gonna test this app on the docker environment

### ISSUE THREAD

**Issue by kimsijin33** [brandiqa/sp-mall-park-wrld#3]
How can I fix the port ?

1234 and 3000  
and this app need third port variable XXXXX

How can I fix bottom variable third port ? 

I used docker port forwarding environment

I'm start this app but show only black screen on the chrome.

I heard sure working this app with only 1234 port and open internet.
and current that status. 

How can I fix it?

Thank you

![image](https://user-images.githubusercontent.com/46598332/107921256-9e42bb00-6fb1-11eb-9575-e0f9f87b4f01.png)

**Comment by brandiqa** [comment]
That's a docker configuration issue you are having which is beyond the scope of this project. Do checkout my other article,https://www.sitepoint.com/docker-windows-10-home/, where I've covered the ports issue.
